spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/jvmc_project_9
spring.datasource.username=usrmvc
spring.datasource.password=Admin$2025
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect