events {
    worker_connections 1024;
}

http {

    log_format lb_log '$remote_addr - [$time_local] "$request" '
                      'status=$status upstream=$upstream_addr '
                      'response_time=${upstream_response_time}s';

    access_log /var/log/nginx/access.log lb_log;

    upstream backend_cluster {
        server backend:9090;
    }
    upstream frontend_cluster {
        server frontend:80; 
    }

    server {
        listen 80;

        # ── Cabecera que identifica qué réplica respondió ────────
        add_header X-Upstream-Addr  $upstream_addr          always;
        add_header X-Served-By      $hostname               always;
        add_header X-Response-Time  $upstream_response_time always;

        # ── Proxy al backend ─────────────────────────────────────────────────────
        location /api/ {
            proxy_pass         http://backend_cluster/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;

            # Timeouts
            proxy_connect_timeout 5s;
            proxy_read_timeout    30s;
        }

        # ── Proxy al frontend Angular ─────────────────────────────────────────────
        location / {
            proxy_pass         http://frontend_cluster/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}